name: woody_lints
description: Woody's custom lint rules for Flutter projects.
version: 1.0.0

# pub.dev에 올리지 않고 개인적으로 사용
publish_to: 'none'

# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.10.4

# Add regular dependencies here.
dependencies:
  # path: ^1.9.0

dev_dependencies:
  lints: ^6.0.0
