name: woody_lints
description: Woody's custom lint rules for Flutter projects.
version: 1.2.0

# pub.dev에 올리지 않고 개인적으로 사용
publish_to: 'none'

repository: https://github.com/woodkill/woody_lints.git

environment:
  sdk: ^3.10.4

# Add regular dependencies here.
dependencies:
  # path: ^1.9.0

dev_dependencies:
  flutter_lints: ^6.0.0
